auth:
  htpasswd:
    file: ./htpasswd
    max_users: 100

store:
  aws-s3-storage:
    bucket: verdaccio
    region: us-east-1
    endpoint: https://minio.adric.me
    forcePathStyle: true
    keyPrefix: packages/

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  "@miempresa/*":
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  "**":
    access: $all
    publish: $authenticated
    proxy: npmjs
