version: '3.8'

services:
  verdaccio:
    image: verdaccio/verdaccio
    ports:
      - "4873:4873" # <-- Esto expone el servicio a tu red local
    volumes:
      - verdaccio-storage:/verdaccio/storage
      - verdaccio-plugins:/verdaccio/plugins
      - ./conf:/verdaccio/conf
    restart: unless-stopped

volumes:
  verdaccio-storage:
  verdaccio-plugins: