version: '3.8'

services:
  verdaccio:
    build: .
    ports:
      - "4873:4873" # <-- Esto expone el servicio a tu red local
    volumes:
      - verdaccio-storage:/verdaccio/storage
      - verdaccio-plugins:/verdaccio/plugins
    restart: unless-stopped

volumes:
  verdaccio-storage:
  verdaccio-plugins: