version: '3.8'

services:
  verdaccio:
    build: .
    ports:
      - "4873:4873" # <-- Esto expone el servicio a tu red local
    volumes:
      - verdaccio-storage:/verdaccio/storage
      - verdaccio-plugins:/verdaccio/plugins
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4873"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  verdaccio-storage:
  verdaccio-plugins: