services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: verdaccio
    restart: always
    ports:
      - "4873:4873"
    volumes:
      - verdaccio-storage:/verdaccio/storage
      - ./conf/config.yaml:/verdaccio/conf/config.yaml
    environment:
      - VERDACCIO_PORT=4873

volumes:
  verdaccio-storage:
  verdaccio-conf:
